"""Added a models

Revision ID: b4bf3c2df9b1
Revises: 
Create Date: 2022-02-15 14:38:52.991550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bf3c2df9b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=200), nullable=False),
    sa.Column('app_id', sa.String(length=40), nullable=False),
    sa.Column('app_secret', sa.String(length=128), nullable=False),
    sa.Column('date_of_add', sa.DateTime(), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id'),
    sa.UniqueConstraint('app_name')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('date_of_add', sa.DateTime(), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=True)
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('redirect_url', sa.String(length=300), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('date_of_add', sa.DateTime(), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('redirect_url'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
